chore: update tests

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -42,12 +42,34 @@ jobs:
       dispatcher_runner_label_aliases: 'self-hosted=github-action-dispatcher-integration'
       dispatcher_disable_default: false
 
-  # This should not fail with 404 on runs-on label because we allow for
-  # fallback to the default runner pool for allowlisted labels without a match.
-  test-default-success:
-    name: 'test-default-success[SUCCESS_EXPECTED]'
+  # Initially this org-pool is not setup in the discovery job so when the
+  # dispatcher looks it up it is missing. The dispatcher allows this label but
+  # there is no default pool configured for this label.
+  # This should fail with 404 on runs-on label.
+  test-missing-org-pool-does-not-default:
+    name: 'test-missing-org-pool-default-success[FAILURE_EXPECTED]'
     needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
     runs-on: 'github-action-dispatcher-2-integration'
+    steps:
+      - name: 'I SHOULD NOT RUN'
+        run: |
+          echo "OH NO..."
+
+  # This pool is only configured for default.
+  test-finds-default-pool:
+    name: 'test-finds-default-pool[SUCCESS_EXPECTED]'
+    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
+    runs-on: 'github-action-dispatcher-integration'
+    steps:
+      - name: 'I SHOULD RUN'
+        run: |
+          echo "OH YEAH..."
+
+  # This aliased pool is only configured for default.
+  test-finds-default-pool-with-alias:
+    name: 'test-finds-default-pool-with-alias[SUCCESS_EXPECTED]'
+    needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
+    runs-on: 'self-hosted'
     steps:
       - name: 'I SHOULD RUN'
         run: |
@@ -63,8 +85,12 @@ jobs:
         run: |
           echo "OH NO..."
 
+  # After disabling default fallback, only pools configured to directly handle
+  # the abcxyz org should pick up jobs. Otherwise they go to the 404 runner.
+  # No pools initially are configured in the discovery that have the abcxyz org
+  # scope. So ALL JOBS SHOULD FAIL.
   deploy-dispatcher-no-default:
-    needs: ['test-default-success']
+    needs: ['test-org-pool-default-success', 'test-finds-default-pool', 'test-finds-default-pool-with-alias']
     uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
     with:
       deploy_dispatcher: true
@@ -73,10 +99,19 @@ jobs:
       dispatcher_runner_label_aliases: 'self-hosted=github-action-dispatcher-integration'
       dispatcher_disable_default: true
 
-  # Now that default is disabled, confirm that we still can use a pool that is
-  # correctly configured.
-  test-finds-assigned-pool:
-    name: 'test-finds-assigned-pool[SUCCESS_EXPECTED]'
+  # We induce a sleep so that we can confirm that some time delta occurred and
+  # that indeed deploying the dispatcher with the job-2 runs-on label
+  # correctly picks up the pending job from test-go-version.
+  sleep-1-min:
+    needs: ['deploy-dispatcher-no-default']
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: 'Sleep 60 seconds'
+        run: |
+          sleep 60s
+
+  test-does-not-find-default-pool:
+    name: 'test-does-not-find-default-pool[FAILURE_EXPECETED]'
     needs: ['deploy-dispatcher-no-default']
     runs-on: 'github-action-dispatcher-integration'
     steps:
@@ -84,21 +119,10 @@ jobs:
         run: |
           echo "OH YEAH..."
 
-  # Now that default is disabled, confirm that we can still use a pool that is
-  # correctly configured via alias.
-  test-finds-assigned-pool-with-alias:
-    name: 'test-finds-assigned-pool[SUCCESS_EXPECTED]'
-    needs: ['deploy-dispatcher-no-default']
-    runs-on: 'self-hosted'
-    steps:
-      - name: 'I SHOULD RUN'
-        run: |
-          echo "OH YEAH..."
-
   # This should fail with 404 on runs-on label because the label is allowlisted,
   # there is no assigned pool, and fallback to default runners is disabled.
-  test-does-not-default:
-    name: 'test-does-not-default[FAILURE_EXPECETED]'
+  test-does-not-find-missing-org-pool:
+    name: 'test-does-not-find-missing-org-pool[FAILURE_EXPECETED]'
     needs: ['deploy-dispatcher-no-default']
     runs-on: 'github-action-dispatcher-2-integration'
     steps:
@@ -106,8 +130,10 @@ jobs:
         run: |
           echo "OH NO..."
 
+  # Now we turn on the github-action-dispatcher-2-integration pool which is
+  # scoped to abcxyz org. So this jobs sent to this label should succeed.
   deploy-runner-discovery-job-with-runner-2:
-    needs: ['test-finds-assigned-pool', 'test-finds-assigned-pool-with-alias']
+    needs: ['sleep-1-min']
     uses: './.github/workflows/deploy-integration.yml' # ratchet:exclude
     with:
       deploy_dispatcher: false
@@ -115,10 +141,8 @@ jobs:
       supported_runner_labels: 'github-action-dispatcher-integration,github-action-dispatcher-2-integration,self-hosted'
 
   # This should now succeed because we have an assigned pool for this.
-  # TODO: Enable once logic for orgs in discovery / dispatcher is implemented.
   test-found-pool-for-label-after-discovery-updates-with-label:
     name: 'test-gad-2-label-in-discovery[SUCCESS_EXPECTED]'
-    if: 'false'
     needs: ['deploy-runner-discovery-job-with-runner-2']
     runs-on: 'github-action-dispatcher-2-integration'
     steps:
@@ -130,15 +154,31 @@ jobs:
     if: |-
       ${{ always() }}
     needs: [
-      'test-finds-assigned-pool',
-      'test-finds-assigned-pool-with-alias',
+      # FAILURES
+      'test-missing-org-pool-does-not-default',
       'test-unknown-label',
-      'test-does-not-default',
-      'test-found-pool-for-label-after-discovery-updates-with-label']
+      'test-does-not-find-default-pool',
+      'test-does-not-find-missing-org-pool',
+      # SUCCESSES
+      'test-finds-default-pool',
+      'test-finds-default-pool-with-alias',
+      'test-found-pool-for-label-after-discovery-updates-with-label'
+      ]
     runs-on: 'ubuntu-latest'
     permissions:
       contents: 'read'
     steps:
+      #############
+      # FAILURES
+      #############
+      - name: 'Assert test-missing-org-pool-does-not-default fails'
+        if: |-
+          ${{ needs.test-missing-org-pool-does-not-default.result != 'failure' }}
+        run: |
+          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-missing-org-pool-does-not-default.result }}"
+          exit 1
+
       - name: 'Assert test-unknown-labal fails'
         if: |-
           ${{ needs.test-unknown-label.result != 'failure' }}
@@ -147,36 +187,43 @@ jobs:
           echo "::error::Status: ${{ needs.test-unknown-label.result }}"
           exit 1
 
-      - name: 'Assert test-does-not-default Test fails'
+      - name: 'Assert test-does-not-find-default-pool fails'
         if: |-
-          ${{ needs.test-does-not-default.result != 'failure' }}
+          ${{ needs.test-does-not-find-default-pool.result != 'failure' }}
         run: |
           echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
-          echo "::error::Status: ${{ needs.test-does-not-default.result }}"
+          echo "::error::Status: ${{ needs.test-does-not-find-default-pool.result }}"
           exit 1
 
-      - name: 'Assert test-finds-assigned-pool succeeds'
+      - name: 'Assert test-does-not-find-missing-org-pool Test fails'
         if: |-
-          ${{ needs.test-finds-assigned-pool.result != 'success' }}
+          ${{ needs.test-does-not-find-missing-org-pool.result != 'failure' }}
+        run: |
+          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-does-not-find-missing-org-pool.result }}"
+          exit 1
+      #############
+      # SUCCESSES
+      #############
+      - name: 'Assert test-finds-default-pool succeeds'
+        if: |-
+          ${{ needs.test-finds-default-pool.result != 'success' }}
         run: |
           echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
-          echo "::error::Status: ${{ needs.test-finds-assigned-pool.result }}"
+          echo "::error::Status: ${{ needs.test-finds-default-pool.result }}"
           exit 1
 
-      - name: 'Assert test-finds-assigned-pool-with-alias succeeds'
+      - name: 'Assert test-finds-default-pool-with-alias succeeds'
         if: |-
-          ${{ needs.test-finds-assigned-pool-with-alias.result != 'success' }}
+          ${{ needs.test-finds-default-pool-with-alias.result != 'success' }}
         run: |
           echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
-          echo "::error::Status: ${{ needs.test-finds-assigned-pool-with-alias.result }}"
+          echo "::error::Status: ${{ needs.test-finds-default-pool-with-alias.result }}"
           exit 1
 
       - name: 'Assert test-found-pool-for-label-after-discovery-updates-with-label succeeds'
-        # TODO: Re-enable test-found-pool-for-label-after-discovery-updates-with-label once org based labels works.
-        # if: |-
-        #   ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'success' }}
         if: |-
-          ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'skipped' }}
+          ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'success' }}
         run: |
           echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
           echo "::error::Status: ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result }}"
