test: label no run (#275)

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -221,7 +221,7 @@ jobs:
   # We induce a sleep so that we can confirm that some time delta occurred and
   # that indeed deploying the dispatcher with the job-2 runs-on label
   # correctly picks up the pending job from test-go-version.
-  sleep:
+  sleep_1_min:
     needs: ['deploy', 'deploy-runner-discovery-job']
     runs-on: 'ubuntu-latest'
     steps:
@@ -231,7 +231,7 @@ jobs:
 
   deploy-runner-discovery-job-with-runner-2:
     runs-on: 'ubuntu-latest'
-    needs: ['sleep']
+    needs: ['sleep_1_min']
     permissions:
       contents: 'read'
       id-token: 'write'
@@ -290,8 +290,66 @@ jobs:
           echo "deploy_time=${deploy_time}"
           echo "deploy_time=${deploy_time}" >> "${GITHUB_OUTPUT}"
 
+  # This should never execute.
+  test-unknown-label:
+    name: 'test-unknown-label[${{ github.sha }}]'
+    needs: ['deploy', 'deploy-runner-discovery-job']
+    runs-on: 'label-no-run-me'
+    steps:
+      - name: 'I SHOULD NOT RUN'
+        run: |
+          echo "OH NO..."
+
+  # We assume that 4 minutes is sufficient for the job to be picked up under
+  # normal operating circumstances. Note that if there is some intermitent
+  # failure or outage with GitHub this may not be sufficient.
+  sleep_4_min:
+    needs: ['deploy', 'deploy-runner-discovery-job']
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: 'Sleep 240 seconds'
+        run: |
+          sleep 240s
+
+  cancel-or-fail-unknown-label:
+    if: |-
+      ${{ always() }}
+    needs: ['sleep_4_min', 'deploy-runner-discovery-job-with-runner-2', 'test-go-version']
+    runs-on: 'ubuntu-latest'
+    permissions:
+      contents: 'read'
+      actions: 'write'
+    steps:
+      - name: 'Checkout'
+        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
+
+      - name: 'Cancel and check status'
+        env:
+          JOB_NAME: 'smoke-tests / test-unknown-label[${{ github.sha }}]'
+          GH_TOKEN: '${{ github.token }}'
+          RUN_ID: '${{ github.run_id }}'
+        run: |
+          JOB_STATUS=$(gh run view "${RUN_ID}" --json jobs -q ".jobs[] | select(.name == \"${JOB_NAME}\") | .status")
+
+          if [[ "$JOB_STATUS" == "queued" ]]; then
+            echo "Successfully verified that 'label-no-run-me' is queued."
+          else
+            echo "Error: 'label-no-run-me' is not in the expected 'queued' state. Current status: ${JOB_STATUS}"
+            FAIL="true"
+          fi
+
+          echo "Cancelling the workflow run..."
+          gh run cancel "${RUN_ID}"
+          echo "Workflow run cancellation initiated."
+
+          if [[ "${FAIL}" == "true" ]]; then
+            exit 1
+          fi
+
   confirm-test-go-version-ran:
-    needs: ['deploy-runner-discovery-job-with-runner-2', 'test-go-version']
+    if: |-
+      ${{ always() }}
+    needs: ['deploy-runner-discovery-job-with-runner-2', 'test-go-version', 'cancel-or-fail-unknown-label']
     runs-on: 'ubuntu-latest'
     steps:
       # TODO: Confirm that the execution time for the test-go-version[github-action-dispatcher-2-integration]
