chore: address comments

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -211,9 +211,9 @@ jobs:
             --format='value(status.url)'
 
   # This should not fail with 404 on runs-on label because we allow for
-  # default to the default runner pool for allowlisted labels without a match.
+  # fallback to the default runner pool for allowlisted labels without a match.
   test-default-success:
-    name: 'test-default-success[${{ github.sha }}]'
+    name: 'test-default-success[SUCCESS_EXPECTED]'
     needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
     runs-on: 'github-action-dispatcher-2-integration'
     steps:
@@ -223,7 +223,7 @@ jobs:
 
   # This should fail with 404 on runs-on label.
   test-unknown-label:
-    name: 'test-unknown-label[${{ github.sha }}]'
+    name: 'test-unknown-label[FAILURE_EXPECTED]'
     needs: ['deploy-dispatcher-with-default', 'deploy-runner-discovery-job']
     runs-on: 'label-no-run-me'
     steps:
@@ -305,7 +305,7 @@ jobs:
   # Now that default is disabled, confirm that we still can use a pool that is
   # correctly configured.
   test-finds-assigned-pool:
-    name: 'test-finds-assigned-pool[${{ github.sha }}]'
+    name: 'test-finds-assigned-pool[SUCCESS_EXPECTED]'
     needs: ['deploy-dispatcher-no-default']
     runs-on: 'github-action-dispatcher-integration'
     steps:
@@ -316,7 +316,7 @@ jobs:
   # Now that default is disabled, confirm that we can still use a pool that is
   # correctly configured via alias.
   test-finds-assigned-pool-with-alias:
-    name: 'test-finds-assigned-pool[${{ github.sha }}]'
+    name: 'test-finds-assigned-pool[SUCCESS_EXPECTED]'
     needs: ['deploy-dispatcher-no-default']
     runs-on: 'self-hosted'
     steps:
@@ -325,9 +325,9 @@ jobs:
           echo "OH YEAH..."
 
   # This should fail with 404 on runs-on label because the label is allowlisted,
-  # there is no assigned pool, and default to default is disabled.
+  # there is no assigned pool, and fallback to default runners is disabled.
   test-does-not-default:
-    name: 'test-does-not-default[${{ github.sha }}]'
+    name: 'test-does-not-default[FAILURE_EXPECETED]'
     needs: ['deploy-dispatcher-no-default']
     runs-on: 'github-action-dispatcher-2-integration'
     steps:
@@ -399,7 +399,7 @@ jobs:
   # This should now succeed because we have an assigned pool for this.
   # TODO: Enable once logic for orgs in discovery / dispatcher is implemented.
   test-found-pool-for-label-after-discovery-updates-with-label:
-    name: 'test-gad-2-label-in-discovery[${{ github.sha }}]'
+    name: 'test-gad-2-label-in-discovery[SUCCESS_EXPECTED]'
     if: 'false'
     needs: ['deploy-runner-discovery-job-with-runner-2']
     runs-on: 'github-action-dispatcher-2-integration'
@@ -411,35 +411,57 @@ jobs:
   smoke-tests-passed:
     if: |-
       ${{ always() }}
-    needs: ['test-finds-assigned-pool', 'test-finds-assigned-pool-with-alias', 'test-unknown-label', 'test-does-not-default', 'test-found-pool-for-label-after-discovery-updates-with-label']
+    needs: [
+      'test-finds-assigned-pool',
+      'test-finds-assigned-pool-with-alias',
+      'test-unknown-label',
+      'test-does-not-default',
+      'test-found-pool-for-label-after-discovery-updates-with-label']
     runs-on: 'ubuntu-latest'
     permissions:
       contents: 'read'
     steps:
-      - name: 'Check unknown-labal Test Status'
-        # We expect the result of the test to be failed.
+      - name: 'Assert test-unknown-labal fails'
         if: |-
-          ${{ needs.test-unknown-label.result != 'failure' || needs.test-does-not-default.result != 'failure' }}
-        env:
-          RESULT_UNKNOWN: '${{ needs.test-unknown-label.result }}'
-          RESULT_NO_DEFAULT: '${{ needs.test-does-not-default.result }}'
+          ${{ needs.test-unknown-label.result != 'failure' }}
         run: |
-          echo "::error::Smoke Test succeeded or was skipped. Failing status check to block merge. Status: ${RESULT_UNKNOWN} ${RESULT_NO_DEFAULT}"
+          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-unknown-label.result }}"
           exit 1
 
-      - name: 'Check Success Test Status'
-        # We expect the result of the test to be success.
-        # TODO: Re-enable test-found-pool-for-label-after-discovery-updates-with-label once org based labels works.
+      - name: 'Assert test-does-not-default Test fails'
         if: |-
-          ${{ needs.test-finds-assigned-pool.result != 'success' || needs.test-finds-assigned-pool-with-alias.result != 'success' || needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'skipped' }}
-        # if: |-
-        #   ${{ needs.test-finds-assigned-pool.result != 'success' || needs.test-finds-assigned-pool-with-alias.result != 'success' || needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'success' }}
-        env:
-          RESULT_ASSIGNED_POOL: '${{ needs.test-finds-assigned-pool.result }}'
-          RESULT_ASSIGNED_POOL_WITH_ALIAS: '${{ needs.test-finds-assigned-pool-with-alias.result }}'
-          RESULT_FOUND_LABEL_AFTER_DISCOVERY: '${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result }}'
+          ${{ needs.test-does-not-default.result != 'failure' }}
         run: |
-          echo "::error::Smoke Test failed or was skipped. Failing status check to block merge. Status: ${RESULT_ASSIGNED_POOL} ${RESULT_ASSIGNED_POOL_WITH_ALIAS} ${RESULT_FOUND_LABEL_AFTER_DISCOVERY}"
+          echo "::error::Smoke Test succeeded or was skipped. Expected failure. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-does-not-default.result }}"
+          exit 1
+
+      - name: 'Assert test-finds-assigned-pool succeeds'
+        if: |-
+          ${{ needs.test-finds-assigned-pool.result != 'success' }}
+        run: |
+          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-finds-assigned-pool.result }}"
+          exit 1
+
+      - name: 'Assert test-finds-assigned-pool-with-alias succeeds'
+        if: |-
+          ${{ needs.test-finds-assigned-pool-with-alias.result != 'success' }}
+        run: |
+          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-finds-assigned-pool-with-alias.result }}"
+          exit 1
+
+      - name: 'Assert test-found-pool-for-label-after-discovery-updates-with-label succeeds'
+        # TODO: Re-enable test-found-pool-for-label-after-discovery-updates-with-label once org based labels works.
+        # if: |-
+        #   ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'success' }}
+        if: |-
+          ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result != 'skipped' }}
+        run: |
+          echo "::error::Smoke Test failed or was skipped. Expected success. Failing status check to block merge."
+          echo "::error::Status: ${{ needs.test-found-pool-for-label-after-discovery-updates-with-label.result }}"
           exit 1
 
       - name: 'Confirm tests passed'
